### ISSUE TITLE
IOError: cannot identify image file

### ISSUE THREAD

**Issue by roryw10** [danielvarga/keras-finetuning#5]
Hitting an error here when i run the script, going to have a look around now i think there is something wrong with pillow in my environment though i have tried to create a fresh env and im still hitting the same error!

`Using TensorFlow backend.
loading dataset
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    X, y, tags = dataset.dataset(data_directory, n)
  File "/Users/roryw10/keras-finetuning/dataset.py", line 45, in dataset
    img = scipy.misc.imread(filename)
  File "//anaconda/envs/finetune/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "//anaconda/envs/finetune/lib/python2.7/site-packages/PIL/Image.py", line 1980, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file`

**Comment by danielvarga** [comment]
Sorry for the late reply! If it's still relevant: what's the extension of this image file? Are native libs like libpng properly installed?

**Comment by zack686** [comment]
Hi Daniel,

I have used jpg as the image format. But the thing is that the code only seem to work for one dataset of jpg images so if I change the dataset but the input images are still in  jpg format, I would get this error. It only works on one dataset for some reason.

**Comment by zack686** [comment]
Libpng is installed and I have tried using both png and jpg image format in data_dir.

**Comment by danielvarga** [comment]
Can you open the specific image where the process fails, like this?:

```
from scipy.misc import imread
print imread("path/to/image.png").shape
```

**Comment by sivaguru-nathan** [comment]
@danielvarga  i also having same error
from scipy.misc import imread
print imread(" ").shape
this showing the same error "cannot identify image file"

**Comment by gauravgola96** [comment]
Hey,
I am also facing same problem when i tried to use keras Imagegenrator().flow_from_dataframe . 
Any solution so far?
