### ISSUE TITLE
AssertionError in dataset.py line 47

### ISSUE THREAD

**Issue by heikog** [danielvarga/keras-finetuning#7]
Hi,
when I run train.py  on some test data I get the following error.
Any advise ?

```
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    X, y, tags = dataset.dataset(data_directory, n)
  File "dataset.py", line 47, in dataset
    assert chan == 3

AssertionError
```

**Comment by heikog** [comment]
if anyone else runs into that error: was some problem with the image - delteing it from the collection of fotos solved it
